library(shiny)
library(shinydashboard)

shinyUI(dashboardPage(skin = "green",
	 dashboardHeader(title = "GUI for MCP"),
   	dashboardSidebar(
	    sidebarMenu(
   		 menuItem("CHARTING", tabName = "dashboard", icon = icon("line-chart")),
    	 menuItem("GETTING STARTED", icon = icon("question-circle"), tabName = "widgets")
  			),
  		br(),
  		br(),
  		textInput("player1","Player Who Serves First","Serving First"),
      textInput("player1_hand","Hand","Right or Left"),
  		textInput("player2","Player Who Returns First","Returning First"),
      textInput("player2_hand","Hand","Right or Left"),
  		textInput("tour","Tour","ATP or WTA"),
   		textInput("date","Date of Match","MMDDYYYY"),
  		textInput("time","Local Time","HH:MM AM/PM"),   		
  		textInput("tournament","Tournament","Tournament"), 
  		textInput("round","Round","R128, R64, etc"), 
  		checkboxInput("bestof5", label = "Best of 5?", value = FALSE),	
  		checkboxInput("finaltb", label = "Final Tiebreak?", value = FALSE),	
  		textInput("court","Court","Centre, Grandstand, etc"), 
  		textInput("surface","Surface","Indoor Hard, Outdoor Grass, etc"),   		
  		textInput("umpire","Umpire","Name"), 	
  		textInput("charter","Charted By","Name"),
  		br(),
		textInput("filename","Saving Your Work","Enter Chart Filename"),
		div(style = "margin:5%;", downloadButton('downloadData', 'Download'))
	  	),
	  dashboardBody(      
    tags$head(tags$style("#score_table table {background-color: #EFEEEC; font-size: 16px; width: 100%}", media="screen", type="text/css")),
	    tabItems(
    		tabItem(tabName = "dashboard",
    		fluidRow(
    		 	column(width = 8, 
    		      column(width = 12, box(width = "100%", (div(style = "height:100px;", valueBoxOutput("first_score", width = "100%"))))),
    		      column(width = 12, 
    		   	  	column(width = 4, actionButton("new", p("Next point", style="font-size:14px;"), width = "100%")),
    		   	  	column(width = 4, actionButton("reset", p("Reset current", style="font-size:14px;"), width = "100%")),
    		   	  	column(width = 4, actionButton("resetLast", p("Reset last", style="font-size:14px;"), width = "100%")))
              ),
          column(width = 4, box(title = "Scoreboard", tableOutput('score_table'), solidHeader = TRUE, width = "100%", status = "success"))
        ),
          column(width = 10, div(p(textOutput("pointer")), style = "font-size:20px;font-style:italic;")),
          tabBox(
            title = h3(em("Charting the Point"), style = "color: gray;"), height = "550px", width = 11, side = "left",
            tabPanel(p("Serve", style="font-size: 18px;"),
           column(width = 3, 
             box(title = "Lets", status = "primary", solidHeader = TRUE, width = "100%", height = 320,
             actionButton("let", "Let", width = "100%"),
             actionButton("time", "Time violation", width = "100%"))),
          column(width = 3,  
            box(title = "Direction", status = "primary", solidHeader = TRUE, width = "100%", height = 200,
              actionButton("outwide", "Wide", width = "100%"),
              actionButton("body", "Body", width = "100%"),
              actionButton("downthenet", "Down the T", width = "100%"),
              actionButton("unknown_direction", "Unknown", width = "100%")),
            box(title = "Serve and Volley", status = "primary", width = "100%", solidHeader = TRUE, height = 100,
              actionButton("serve_volley", "Server Approached", width = "100%"))),
            column(width = 3,          
              box(title = "Fault", status = "primary", solidHeader = TRUE, width = "100%", height = 320,
              actionButton("net_serve", "Net", width = "100%"),
              actionButton("wide", "Wide", width = "100%"),
              actionButton("deep", "Deep", width = "100%"),
              actionButton("wide_deep", "Wide and deep", width = "100%"),
              actionButton("foot_fault", "Foot fault", width = "100%"),
              actionButton("unknown_fault", "Unknown", width = "100%")))
              ),
            tabPanel(p("Rally Sequence", style="font-size: 18px;"),
       column(width = 5, 
       column(width = 6,
            box(title = "Forehand", status = "primary", width = "100%", solidHeader = TRUE,
              actionButton("ground_forehand", "Groundstroke", width = "100%"),
              actionButton("slice_forehand", "Slice", width = "100%"),
              actionButton("volley_forehand", "Volley", width = "100%"),
                actionButton("halfvolley_forehand", "Half-volley", width = "100%"),
                actionButton("swingvolley_forehand", "Swing Volley", width = "100%"),
                actionButton("overhead_forehand", "Overhead", width = "100%"),
              actionButton("drop_forehand", "Drop Shot", width = "100%"),
              actionButton("lob_forehand", "Lob", width = "100%"),
          actionButton("trick", "Trick shot", width = "100%"),
          actionButton("unknown_shot", "Unknown", width = "100%"))),
      column(width = 6,      
          box(title = "Backhand", status = "primary", width = "100%", solidHeader = TRUE,
              actionButton("ground_backhand", "Groundstroke", width = "100%"),
              actionButton("slice_backhand", "Slice", width = "100%"),
              actionButton("volley_backhand", "Volley", width = "100%"),
                actionButton("halfvolley_backhand", "Half-volley", width = "100%"),
                actionButton("swingvolley_backhand", "Swing Volley", width = "100%"),
                actionButton("overhead_backhand", "Overhead", width = "100%"),
              actionButton("drop_backhand", "Drop Shot", width = "100%"),
              actionButton("lob_backhand", "Lob", width = "100%"),
          actionButton("trick", "Trick shot", width = "100%"),
          actionButton("unknown_shot", "Unknown", width = "100%")))
        ),
      column(width = 7,
        fluidRow(
        column(width = 4, 
          box(title = "Position (optional)", status = "primary", width = "100%", solidHeader = TRUE,
          actionButton("approach", "Approach shot", width = "100%"),
          actionButton("net", "Net", width = "100%"),         
          actionButton("baseline_shot", "Baseline", width = "100%"),
          actionButton("clipped", "Clipped net", width = "100%"))),
         column(width = 4,
          box(title = "Direction", status = "primary", width = "100%", solidHeader = TRUE, height = 200,
            actionButton("right", "Right side", width = "100%"),
           actionButton("middle", "Middle", width = "100%"),
           actionButton("left", "Left side", width = "100%"),
           actionButton("unknown_stroke_direction", "Unknown", width = "100%"))),
         column(width = 4, 
          box(title = "Depth of Shot", status = "primary", solidHeader = TRUE, width = "100%", height = 200,
            actionButton("within", "Service Box", width = "100%"),
            actionButton("behind", "Before Baseline", width = "100%"),
            actionButton("baseline", "At Baseline", width = "100%"),
            actionButton("unknown_depth", "Unknown", width = "100%")))
         ),
        fluidRow(
         h2("Shortcuts for Common Shots", style = "margin-top:0;margin-bottom:1%;margin-left:2%;font-size:20px;"),
    	 column(width = 4, 
           actionButton("seq1", "FH-Right-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq2", "FH-Right-Before Baseline", width = "100%", style = "text-align:left;"),        
           actionButton("seq3", "FH-Right-Baseline", width = "100%", style = "text-align:left;"),
           actionButton("seq4", "BH-Right-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq5", "BH-Right-Before Baseline", width = "100%", style = "text-align:left;"),
           actionButton("seq6", "BH-Right-Baseline", width = "100%", style = "text-align:left;")),
         column(width = 4,
           actionButton("seq7", "FH-Middle-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq8", "FH-Middle-Before Baseline", width = "100%", style = "text-align:left;"),
           actionButton("seq9", "FH-Middle-Baseline", width = "100%", style = "text-align:left;"),
           actionButton("seq10", "BH-Middle-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq11", "BH-Middle-Before Baseline", width = "100%", style = "text-align:left;"),         
           actionButton("seq12", "BH-Middle-Baseline", width = "100%", style = "text-align:left;")),
         column(width = 4, 
           actionButton("seq13", "FH-Left-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq14", "FH-Left-Before Baseline", width = "100%", style = "text-align:left;"),         
           actionButton("seq15", "FH-Left-Baseline", width = "100%", style = "text-align:left;"),
           actionButton("seq16", "BH-Left-Box", width = "100%", style = "text-align:left;"),
           actionButton("seq17", "BH-Left-Before Baseline", width = "100%", style = "text-align:left;"),         
           actionButton("seq18", "BH-Left-Baseline", width = "100%", style = "text-align:left;"))))
              ),
            tabPanel(p("Point Ending", style="font-size: 18px;"), 
            column(width = 3,
              box(title = "Service Winner", status = "primary", solidHeader = TRUE, width = "100%", height = 290,
              actionButton("ace", "Ace", width = "100%"),
              actionButton("unreturnable", "Unreturnable", width = "100%"))),
                      column(width = 3,
            box(title = "Type of Error", status = "primary", solidHeader = TRUE, width = "100%", height = 290,
            actionButton("net_error", "Net", width = "100%"),
            actionButton("wide_error", "Wide", width = "100%"),
            actionButton("deep_error", "Deep", width = "100%"),
            actionButton("wide_deep_error", "Wide and deep", width = "100%"),
            actionButton("shank", "Shank", width = "100%"),
            actionButton("unknown_error", "Unknown", width = "100%"))),
            column(width = 3,
              box(title = "Rally Ending", status = "primary", width = "100%", solidHeader = TRUE, height = 290,
              actionButton("winner", "Winner", width = "100%"),
              actionButton("forced", "Forced error", width = "100%"),
              actionButton("unforced", "Unforced error", width = "100%")))))),
     tabItem(tabName = "widgets",
     		 h1("Getting Started"),
     		 h3("This site is a companion tool for the",a("Match Charting Project", href = "http://www.tennisabstract.com/blog/2015/09/23/the-match-charting-project-quick-start-guide/"),". We are living in the ",em("Moneyball")," era, yet analytics in tennis are widely considered some of the", a("least innovative", href = "https://www.youtube.com/watch?v=QPyVJbKjmaw"), "of all sports. The MCP wants to change all of that by making richer data about the events in a tennis match available to the public."),
          h3("The goal of the MCP is to build a database of matches in which every shot is described in detail (type, direction, depth, etc.). Scored matches are added to a growing database that can be used to gain insights about the game."),
     		 	h3(em("The purpose of this dashboard is to make it easy and fun to chart.")),
          div(img(src='diagram.png', width="400px"), style="float:right;padding:2%;"),
          h2("Charting a Point"),
          h3("At the most basic level, a point is made up of a serve, a rally (if the serve is returned), and an ending. The key characteristics of each of these events are shown in boxes in the diagram to the right. Optional descriptions are enclosed in '<>'."),
          h3("The dashboard provides buttons for each characteristic of a shot. Charting the point is as simple as pressing buttons as the events in the point happen. When the point is done, select 'Next Point' to continue. The point, game, and set scores are updated automatically to help keep you on track."),
          h2("Serve", style="text-decoration:underline;"),
          div(img(src='court_serve.png', height="350px"), style="float:left;padding:1%;"),
          h3("The description of the serve must have a direction and the type of fault, if it occurs. There are three possible descriptions for direction: down the T, body, and wide. There is always some subjectivity with these things, but to help give some guidance, the diagram on the left gives approximate locations for each direction type."),
          h3("Some (but not all) of the most common regions for the fault types are shown in the diagram to the left."),
          h3("Lets and time violations can also be noted, as many times as they occur."),
          h3("Another optional description are serve and volley attempts. If the server goes to net, it can be indicated by selecting the `Server Approaches' button. This description would be entered after the direction and would be used no matter the outcome of the serve."),
          h3(em("Order Matters!"), "The order of descriptions for a serve is: Time Violation -> Let -> Direction -> Approach -> (Fault)."),         
          h2("Rally", style="text-decoration:underline;"),
          div(img(src='fault.png', height="350px"), style="float:right;padding:1%;"), 
          h3("If the serve is returned, each subsequent stroke is described. The required descriptions are the type of shot and the direction of the shot. There are a number of possible classifications for the type of shot and if you are ever unsure you can always say unknown. The direction is more stratightforward as it is with respect to the position of the opponent, either to their left, right, or middle (a 'body' shot). Although not required, charters are encouraged to also indicate the depth of the shot using the same classifications as for the return of serve."),
          h3("To help speed up your charting, shortcuts that include shot-direction-depth all in one button are provided for some of the most commont shot types in the bottom right of the `Rally sequence' tab."),          
          h3(em("Order Matters!"), "The order of rally descriptions is: Type -> Position -> Direction -> Depth."),
          h2("Ending", style="text-decoration:underline;"),
          h3("The type of ending (winner, forced error, or unforced error) is the only required description. As for distinguishing forced from unforced errors, MCP creator Jeff Sackmann says 'In general, first-serve return errors are usually forced, and second-serve return errors are often unforced'."),
          h3("An optional description is the shot that was attempted when an error occurred."),
          h2("Ready to Chart?!", style="text-decoration:underline;"),
          h3("Start by filling out the information about the match being played using the text boxes on the sidebar. Make sure to give a filename and save your match as you go along. After 1 hour of inactivity, the entries will be lost."),
          h3("To enter descriptions of a point, use the panel at the center of the screen as depicted in the image to the right. Start with the 'Serve' tab. Note that a fault on the first serve will be automatically detected and progress to the second serve."),         
          div(img(src='tabs.png', width="600px"), style="float:right;padding:1%;"), 
          h3("When a rally occurs, select the 'Rally Sequence' tab (highlighted in the diagram on the right) to enter the description of the rally, however long it lasts."),
          h3("Finally, provide a description of how the point ended with the 'Point Ending' tab."), 
          h3("When the point is finished, select 'Next point'. There are also buttons to clear the current or previous point in case you need to make a correction as you go along."),
     		 	h3("The coded point is described at the top of the page and the current score of the match is shown in the scoreboard at the top right. All points are stored on the server and the complete set of points can be downloaded at any time, using the download command on the left sidebar."),
     	h2("Chart Submission", style="text-decoration:underline;"),	 	
           h3("When your chart is completed, download the CSV and you can send it as-is to the project maintainer, Jeff Sackmann (",code("jeffsackmann@gmail.com"),"), for inclusion in the MCP. If you had to use multiple files for a single match, you will need to append and format these manually before sending."),      		 	
          h2("Resources", style="text-decoration:underline;"),
     		 	h3("For further information about contributing to the MCP, visit this", a("site", href = "http://www.tennisabstract.com/blog/2015/09/23/the-match-charting-project-quick-start-guide/"), "."),
     		 	h3("For questions or feedback about this site, contact",code("s.a.kovalchik@gmail.com."))
     		   )
        )
     )
  )
)